# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

print(f"NumPy version: {np.__version__}")
print(f"NumPy configuration:")
np.show_config()


NumPy version: 1.25.2
NumPy configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language =

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
my_list = [1, 2, 3, 4, 5]

# list to NumPy array
my_array = np.array(my_list)

print(my_array)


[1 2 3 4 5]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [4]:
nine_zeros = np.zeros(9)
print(nine_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
# array yaratish
my_array = np.array([1, 2, 3, 4, 5])

# xotira hajmini topish
memory_size = my_array.size * my_array.itemsize

# print
print(f"Memory size of the array: {memory_size} bytes")


Memory size of the array: 40 bytes


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
!python -c "import numpy as np; np.info(np.add)"


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [7]:
# array zeros
vector = np.zeros(12)

# Set 6 element to 1
vector[5] = 1

# Print
print(vector)


[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [8]:
# Create a vector of values from 20 to 59
vector = np.arange(20, 60)

# Print
print(vector)


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [9]:
# Create a vector
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector
reversed_vector = vector[::-1]

# Print
print(reversed_vector)


[5 4 3 2 1]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
# Create a 3x3 matrix with values from 12 to 20
matrix = np.arange(12, 21).reshape(3, 3)

# Print the matrix
print(matrix)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
matrix = np.array([3, 7, 0, 0, 9, 0])

# nolga teng emas elementlar indeksi
non_zero_indices = np.nonzero(matrix)

# Print
print(non_zero_indices)


(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [12]:
random_array = np.random.random((2, 2, 2))

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [13]:
# Create a 9x9 array of random numbers
random_array = np.random.rand(9, 9)

# Find the maximum and minimum values in the array
max_value = random_array.max()
min_value = random_array.min()

# Print the results
print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")


Maximum value: 0.9837487644358599
Minimum value: 0.007373723460507131


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)


nan
False
False
nan
True
False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [15]:
# Create a 6x3 matrix
matrix_a = np.ones((6, 3))

# Create a 3x4 matrix
matrix_b = np.ones((3, 4))

# Multiply the matrices
matrix_product = np.dot(matrix_a, matrix_b)

# Print the result
print(matrix_product)


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [17]:
a = np.array([1, 2])
b = np.array([4, 5])

print("a > b")
print(a > b)
print("a >= b")
print(a >= b)
print("a < b")
print(a < b)
print("a <= b")
print(a <= b)


a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


<ipython-input-18-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-18-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-18-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [19]:
# Ikkita massiv yarating
array_1 = np.array([0, 1, 2, 5, 0])
array_2 = np.array([0, 1, 4])

# Ikkita massiv orasidagi umumiy qiymatlarni topish
common_values = np.intersect1d(array_1, array_2)

# Print
print(common_values)


[0 1]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [20]:
# Create a random array of floats
random_array = np.random.rand(5)

# Method 1: Using the modulo operator
positive_integers = random_array % 1

# Method 2: Using np.floor
positive_integers = np.floor(random_array)

# Method 3: Using astype(int)
positive_integers = random_array.astype(int)

# Method 4: Using np.trunc
positive_integers = np.trunc(random_array)

# Print the results
print("Original array:", random_array)
print("Positive integers (method 1):", positive_integers)
print("Positive integers (method 2):", positive_integers)
print("Positive integers (method 3):", positive_integers)
print("Positive integers (method 4):", positive_integers)


Original array: [0.89193797 0.94488493 0.01109355 0.70257632 0.60450759]
Positive integers (method 1): [0. 0. 0. 0. 0.]
Positive integers (method 2): [0. 0. 0. 0. 0.]
Positive integers (method 3): [0. 0. 0. 0. 0.]
Positive integers (method 4): [0. 0. 0. 0. 0.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [22]:
# Create array
matrix = np.array([
    0,1,2,0,1,2,0,1,2
]).reshape(3, 3)

# print
print(matrix)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [23]:

# Create a random vector of size 10
vector = np.random.rand(10)

# Sort the vector in ascending order
sorted_vector = np.sort(vector)

# Print the sorted vector
print(sorted_vector)

[0.06971577 0.09482788 0.14695931 0.26213274 0.28617855 0.7661992
 0.77231511 0.82917185 0.83980591 0.84476872]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [24]:
# Create two random arrays
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if the two arrays are equal using np.allclose
print(f"Arrays are equal (np.allclose): {np.allclose(A, B)}")

# Check if the two arrays are equal using np.array_equal
print(f"Arrays are equal (np.array_equal): {np.array_equal(A, B)}")


Arrays are equal (np.allclose): False
Arrays are equal (np.array_equal): False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [25]:
# Create a 6x3 matrix
matrix_a = np.ones((6, 3))

# Create a 3x4 matrix
matrix_b = np.ones((3, 4))

# Multiply the matrices
matrix_product = np.dot(matrix_a, matrix_b)

# Print the result
print(matrix_product)


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [26]:
# Create a random vector of size 5
vector = np.random.rand(5)

# Find the index of the maximum value
max_index = np.argmax(vector)

# Set the maximum value to 0
vector[max_index] = 0

# Print the modified vector
print(vector)

[0.5452062  0.31122211 0.68420875 0.8604013  0.        ]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [27]:
# Get today's date
today = np.datetime64('today')

# Calculate yesterday's date
yesterday = today - np.timedelta64(1, 'D')

# Calculate tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')

# Print the dates
print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")

Yesterday: 2024-06-22
Today: 2024-06-23
Tomorrow: 2024-06-24


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [28]:
# Get the first day of January 2016
first_day_of_january = np.datetime64('2016-01-01')

# Get the last day of January 2016
last_day_of_january = np.datetime64('2016-01-31')

# Create a range of dates from the first to the last day of January 2016
dates = np.arange(first_day_of_january, last_day_of_january + 1, dtype='datetime64[D]')

# Print the dates
print(dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [29]:

# Create a random array of positive floats
random_array = np.random.rand(5) * 10

# Method 1: Using the modulo operator
positive_integers_1 = random_array % 1

# Method 2: Using np.floor
positive_integers_2 = np.floor(random_array)

# Method 3: Using astype(int)
positive_integers_3 = random_array.astype(int)

# Method 4: Using np.trunc
positive_integers_4 = np.trunc(random_array)

# Print the results
print("Original array:", random_array)
print("Positive integers (method 1):", positive_integers_1)
print("Positive integers (method 2):", positive_integers_2)
print("Positive integers (method 3):", positive_integers_3)
print("Positive integers (method 4):", positive_integers_4)

Original array: [9.99857128 8.75036008 5.92254759 0.51980997 2.39381857]
Positive integers (method 1): [0.99857128 0.75036008 0.92254759 0.51980997 0.39381857]
Positive integers (method 2): [9. 8. 5. 0. 2.]
Positive integers (method 3): [9 8 5 0 2]
Positive integers (method 4): [9. 8. 5. 0. 2.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [30]:
# Create two small arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate the sum using np.sum
sum_using_np_sum = np.sum(a) + np.sum(b)

# Calculate the sum using np.add.reduce
sum_using_np_add_reduce = np.add.reduce([a, b])

# Print the results
print(f"Sum using np.sum: {sum_using_np_sum}")
print(f"Sum using np.add.reduce: {sum_using_np_add_reduce}")

Sum using np.sum: 21
Sum using np.add.reduce: [5 7 9]


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [40]:
# Create a vector
vector = np.array([1, 2, 3, 4, 5])

expanded_vector = np.concatenate([np.concatenate([vector[i:i+1], np.zeros(3)]) for i in range(len(vector))])

# Print
print(expanded_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [36]:
# Create an array with some duplicate values
array = np.array([1, 2, 2, 3, 4, 4, 5, 5, 5])


counts = np.bincount(array)

# Find the index of the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = array[most_frequent_index]

# Print
print(f"Most frequent value: {most_frequent_value}")
print(f"Number of times the most frequent value occurs: {counts[most_frequent_index]}")


Most frequent value: 4
Number of times the most frequent value occurs: 3


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [38]:
# Create a large NumPy array
large_array = np.random.rand(1000)

# Calculate the sum of all elements using np.sum() with axis=None
sum_of_elements = np.sum(large_array, axis=None)

# Print the sum
print(f"Sum of all elements: {sum_of_elements}")

Sum of all elements: 510.8541604593466
